<script setup lang="ts">
import { ref, onMounted, watch } from 'vue'
import qualitativeService from '@/services/qualitativeService'
import type { SurveyStats, SurveyReport } from '@/types/analytics'

const props = defineProps<{
  projectId: string
}>()

const stats = ref<SurveyStats | null>(null)
const report = ref<SurveyReport | null>(null)
const isLoading = ref(false)

const loadData = async () => {
  isLoading.value = true
  try {
    const [statsRes, reportRes] = await Promise.all([
      qualitativeService.getSurveyStats(props.projectId),
      qualitativeService.getSurveyFeedback(props.projectId)
    ])
    stats.value = statsRes
    report.value = reportRes
  } catch (error) {
    console.error('Failed to load qualitative report:', error)
  } finally {
    isLoading.value = false
  }
}

const formatDate = (dateString?: string) => {
  if (!dateString) return '-'
  return new Date(dateString).toLocaleDateString('en-US', {
    month: 'short', day: 'numeric', year: 'numeric'
  })
}

const getSentimentColor = (sentiment: string) => {
  switch (sentiment) {
    case 'positive': return 'success'
    case 'negative': return 'error'
    case 'mixed': return 'warning'
    default: return 'grey'
  }
}

const getSeverityColor = (severity: string) => {
  switch (severity) {
    case 'critical': return 'error'
    case 'major': return 'warning'
    case 'minor': return 'info'
    default: return 'grey'
  }
}

const getPriorityColor = (priority: string) => {
  switch (priority) {
    case 'high': return 'error'
    case 'medium': return 'warning'
    case 'low': return 'info'
    default: return 'grey'
  }
}

const isExporting = ref(false)
const reportContent = ref<HTMLElement | null>(null)

const loadScript = (src: string) => {
  return new Promise((resolve, reject) => {
    if (document.querySelector(`script[src="${src}"]`)) return resolve(true);
    const script = document.createElement('script');
    script.src = src;
    script.onload = () => resolve(true);
    script.onerror = reject;
    document.head.appendChild(script);
  });
};

const exportToPDF = async () => {
  if (!report.value || isExporting.value) return;
  
  isExporting.value = true;
  try {
    // Load dependencies from CDN
    await Promise.all([
      loadScript('https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js'),
      loadScript('https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js')
    ]);

    const element = reportContent.value;
    if (!element) return;

    // @ts-ignore
    const { jsPDF } = window.jspdf;
    // @ts-ignore
    const canvas = await html2canvas(element, {
      scale: 2, // Higher quality
      useCORS: true,
      logging: false,
      backgroundColor: '#f8fafc' // Match the background
    });

    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'px',
      format: [canvas.width, canvas.height]
    });

    pdf.addImage(imgData, 'PNG', 0, 0, canvas.width, canvas.height);
    pdf.save(`Qualitative_Insights_${props.projectId}_${new Date().toISOString().split('T')[0]}.pdf`);
  } catch (error) {
    console.error('PDF Export failed:', error);
    // Fallback to print if CDN fails
    window.print();
  } finally {
    isExporting.value = false;
  }
}

onMounted(() => {
  loadData()
})

watch(() => props.projectId, () => loadData())
</script>

<template>
  <div class="surveys-view">
    <div class="d-flex align-center justify-space-between mb-8 no-print">
      <div>
        <h1 class="text-h3 font-weight-bold tracking-tight mb-2">Qualitative Insights</h1>
        <p class="text-subtitle-1 text-grey-darken-1">AI-powered analysis of your customer feedback</p>
      </div>
      <div class="d-flex gap-2">
        <v-btn
          color="secondary"
          prepend-icon="mdi-file-pdf-box"
          variant="outlined"
          rounded="lg"
          class="mr-2"
          :loading="isExporting"
          @click="exportToPDF"
        >
          Download PDF
        </v-btn>
        <v-btn color="primary" prepend-icon="mdi-upload" variant="flat" rounded="lg" @click="$emit('go-to-upload')">
          Upload New Data
        </v-btn>
      </div>
    </div>

    <!-- Wrap content in a ref for PDF exporting -->
    <div ref="reportContent" class="report-container pa-6 bg-white rounded-xl shadow-sm mt-4">
      <!-- Print-only header (also used for PDF export capture) -->
      <div v-if="report" class="mb-8 border-b-sm pb-4">
        <h1 class="text-h4 font-weight-bold tracking-tight mb-2">Qualitative Insights Report</h1>
        <p class="text-subtitle-1 text-grey">Generated by Discoveo AI Analysis • {{ report.project_id }}</p>
      </div>

      <template v-if="isLoading && !report">
        <v-row>
          <v-col cols="12" class="text-center pa-13">
            <v-progress-circular indeterminate color="primary" size="64" />
            <div class="mt-4 text-grey">Analyzing qualitative data...</div>
          </v-col>
        </v-row>
      </template>

      <template v-else-if="report">
        <!-- Narrative Overview -->
        <v-card class="narrative-card mb-8 px-6 py-4" elevation="0">
          <v-row align="center">
            <v-col cols="12" md="1" class="text-center">
              <v-avatar color="primary-lighten-5" size="64">
                <v-icon icon="mdi-robot-outline" color="primary" size="32" />
              </v-avatar>
            </v-col>
            <v-col cols="12" md="11">
              <h3 class="text-h6 font-weight-bold mb-1">Executive Summary</h3>
              <p class="text-body-1 text-grey-darken-3 mb-0 italic-narrative">"{{ report.narrative }}"</p>
              <div class="text-caption text-grey mt-2">
                Analyzed by {{ report.model_used }} on {{ formatDate(report.created_at) }}
              </div>
            </v-col>
          </v-row>
        </v-card>

        <!-- Sentiment & Stats -->
        <v-row class="mb-8">
          <v-col cols="12" md="4">
            <v-card class="insight-card h-100" elevation="0">
              <v-card-title class="px-6 pt-6">Sentiment Distribution</v-card-title>
              <v-card-text class="px-6 pb-6 pt-2">
                <div class="mb-4">
                  <div class="d-flex justify-space-between text-caption font-weight-bold mb-1">
                    <span>POSITIVE</span>
                    <span>{{ report.analysis.sentiment_breakdown.positive_pct }}%</span>
                  </div>
                  <v-progress-linear :model-value="report.analysis.sentiment_breakdown.positive_pct" color="success" height="10" rounded />
                </div>
                <div class="mb-4">
                  <div class="d-flex justify-space-between text-caption font-weight-bold mb-1">
                    <span>NEGATIVE</span>
                    <span>{{ report.analysis.sentiment_breakdown.negative_pct }}%</span>
                  </div>
                  <v-progress-linear :model-value="report.analysis.sentiment_breakdown.negative_pct" color="error" height="10" rounded />
                </div>
                <div>
                  <div class="d-flex justify-space-between text-caption font-weight-bold mb-1">
                    <span>NEUTRAL</span>
                    <span>{{ report.analysis.sentiment_breakdown.neutral_pct }}%</span>
                  </div>
                  <v-progress-linear :model-value="report.analysis.sentiment_breakdown.neutral_pct" color="info" height="10" rounded />
                </div>
              </v-card-text>
            </v-card>
          </v-col>

          <v-col v-for="stat in [
            { label: 'TOTAL RESPONSES', value: stats?.total_responses, icon: 'mdi-poll', color: 'primary' },
            { label: 'AVG. RATING', value: stats?.average_rating?.toFixed(2), icon: 'mdi-star', color: 'warning', suffix: '/ 5' }
          ]" :key="stat.label" cols="12" md="4">
            <v-card class="stat-card h-100" elevation="0">
              <v-card-text class="pa-8 text-center">
                <v-avatar :color="`${stat.color}-lighten-5`" size="64" class="mb-4">
                  <v-icon :icon="stat.icon" :color="stat.color" size="32" />
                </v-avatar>
                <div class="text-caption font-weight-bold text-grey">{{ stat.label }}</div>
                <div class="text-h3 font-weight-bold">
                  {{ stat.value }}
                  <span v-if="stat.suffix" class="text-body-1 text-grey">{{ stat.suffix }}</span>
                </div>
              </v-card-text>
            </v-card>
          </v-col>
        </v-row>

        <!-- Key Issues -->
        <div class="mb-6">
          <h2 class="text-h5 font-weight-bold mb-4 d-flex align-center">
            <v-icon icon="mdi-alert-octagon-outline" color="error" class="mr-2" />
            Critical Issues & Pain Points
          </h2>
          <v-row>
            <v-col v-for="issue in report.analysis.key_issues" :key="issue.title" cols="12" md="6">
              <v-card :class="`issue-card issue-${issue.severity}`" elevation="0">
                <v-card-item>
                  <template v-slot:prepend>
                    <v-chip :color="getSeverityColor(issue.severity)" size="small" class="text-uppercase font-weight-bold mr-2">
                      {{ issue.severity }}
                    </v-chip>
                  </template>
                  <v-card-title class="text-subtitle-1 font-weight-bold">{{ issue.title }}</v-card-title>
                  <template v-slot:append>
                    <div class="text-caption font-weight-bold text-grey">
                      {{ issue.affected_users_pct }}% affected
                    </div>
                  </template>
                </v-card-item>
                <v-card-text class="pb-4">
                  {{ issue.description }}
                </v-card-text>
              </v-card>
            </v-col>
          </v-row>
        </div>

        <!-- Themes -->
        <div class="mb-10">
          <h2 class="text-h5 font-weight-bold mb-4 d-flex align-center">
            <v-icon icon="mdi-message-draw" color="primary" class="mr-2" />
            Recurring Themes
          </h2>
          <v-row>
            <v-col v-for="theme in report.analysis.themes" :key="theme.name" cols="12" md="6" lg="4">
              <v-card class="theme-card h-100" elevation="0">
                <v-card-item>
                  <v-card-title class="text-subtitle-1 font-weight-bold">{{ theme.name }}</v-card-title>
                  <template v-slot:append>
                    <v-chip :color="getSentimentColor(theme.sentiment)" size="x-small" variant="flat">
                      {{ theme.sentiment }}
                    </v-chip>
                  </template>
                </v-card-item>
                <v-card-text>
                  <p class="text-body-2 mb-4">{{ theme.description }}</p>
                  <div class="quotes-container">
                    <div v-for="(quote, i) in theme.sample_quotes" :key="i" class="quote text-caption italic text-grey-darken-2">
                      "{{ quote }}"
                    </div>
                  </div>
                </v-card-text>
              </v-card>
            </v-col>
          </v-row>
        </div>

        <!-- Recommendations -->
        <div>
          <h2 class="text-h5 font-weight-bold mb-4 d-flex align-center">
            <v-icon icon="mdi-lightbulb-on-outline" color="success" class="mr-2" />
            Recommended Actions
          </h2>
          <v-row>
            <v-col v-for="rec in report.analysis.recommendations" :key="rec.title" cols="12">
              <v-card class="recommendation-card" elevation="0">
                <v-row no-gutters>
                  <v-col cols="12" md="9" class="pa-6">
                    <div class="d-flex align-center mb-2">
                      <v-chip :color="getPriorityColor(rec.priority)" size="small" label class="mr-3 font-weight-bold text-uppercase">
                        {{ rec.priority }} Priority
                      </v-chip>
                      <h3 class="text-h6 font-weight-bold">{{ rec.title }}</h3>
                    </div>
                    <p class="text-body-2 text-grey-darken-3 mb-0">{{ rec.description }}</p>
                  </v-col>
                  <v-divider :vertical="!$vuetify.display.smAndDown" />
                  <v-col cols="12" md="3" class="pa-6 bg-grey-lighten-5">
                    <div class="text-caption font-weight-bold text-grey mb-1">EXPECTED IMPACT</div>
                    <div class="text-body-2 font-weight-bold text-success">{{ rec.expected_impact }}</div>
                  </v-col>
                </v-row>
              </v-card>
            </v-col>
          </v-row>
        </div>
      </template>

      <template v-else>
        <v-row>
          <v-col cols="12">
            <v-card class="pa-13 text-center rounded-xl border-dashed" variant="outlined" color="primary">
              <v-icon icon="mdi-auto-fix" size="64" class="mb-4" />
              <h2 class="text-h5 font-weight-bold">No Analysis Available</h2>
              <p class="text-body-1 text-grey mb-6">Upload qualitative data to generate AI-powered insights and recommendations.</p>
              <v-btn color="primary" size="large" prepend-icon="mdi-upload" @click="$emit('go-to-upload')">
                Get Started with Upload
              </v-btn>
            </v-card>
          </v-col>
        </v-row>
      </template>
    </div>
  </div>
</template>

<style scoped>
.surveys-view {
  width: 100%;
}

.tracking-tight {
  letter-spacing: -0.025em;
}

.narrative-card {
  border-radius: 20px !important;
  border: 1px solid #e2e8f0 !important;
  background: white !important;
  border-left: 6px solid #6366f1 !important;
}

.italic-narrative {
  font-style: italic;
  line-height: 1.6;
}

.stat-card, .insight-card, .theme-card {
  border-radius: 20px !important;
  border: 1px solid #e2e8f0 !important;
  background: white !important;
}

.issue-card {
  border-radius: 16px !important;
  border: 1px solid #e2e8f0 !important;
  background: white !important;
}

.issue-critical { border-left: 4px solid #ef4444 !important; }
.issue-major { border-left: 4px solid #f59e0b !important; }
.issue-minor { border-left: 4px solid #3b82f6 !important; }

.theme-card {
  transition: transform 0.2s;
}

.theme-card:hover {
  transform: translateY(-5px);
}

.recommendation-card {
  border-radius: 20px !important;
  border: 1px solid #e2e8f0 !important;
  background: white !important;
  overflow: hidden;
}

.quotes-container {
  border-left: 2px solid #f1f5f9;
  padding-left: 12px;
}

.quote {
  margin-bottom: 8px;
  line-height: 1.4;
}

.border-dashed {
  border-style: dashed !important;
}

.text-success { color: #10b981 !important; }

/* Print Styles */
.print-only {
  display: none;
}

@media print {
  .no-print {
    display: none !important;
  }
  
  .print-only {
    display: block !important;
  }

  /* Force hide all external navigation elements */
  .v-navigation-drawer,
  .v-app-bar,
  .v-system-bar,
  .v-bottom-navigation,
  header,
  aside,
  nav,
  .v-btn {
    display: none !important;
  }

  /* Reset main content layout for full-page print */
  .v-main {
    padding: 0 !important;
    margin: 0 !important;
    --v-layout-left: 0px !important;
    --v-layout-top: 0px !important;
  }

  .main-content {
    padding: 0 !important;
    margin: 0 !important;
    background: white !important;
  }

  .v-main {
    padding: 0 !important;
  }

  .surveys-view {
    padding: 0 !important;
  }

  .v-container {
    padding: 0 !important;
    max-width: none !important;
  }

  .insight-card, .stat-card, .issue-card, .theme-card, .recommendation-card, .narrative-card {
    break-inside: avoid;
    border: 1px solid #e2e8f0 !important;
    box-shadow: none !important;
    margin-bottom: 20px !important;
  }

  body {
    background: white !important;
  }
}
</style>



